#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/usr/local/lib/python3.8/dist-packages/neuron/.data"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/usr/local/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/home/szabobogi/BC_modells/CA1_Stacey_2009/x86_64/.libs/libnrnmech.so" "$@"
